[package]
name = "snake-game"
version = "0.1.0"
authors = ["tannersmith <smi19057@byui.edu>"]
edition = "2021"

[dependencies]
piston = "0.53.1"
piston2d-graphics = "0.41.0"
pistoncore-glutin_window = "0.69.0"
piston2d-opengl_graphics = "0.79.0"
rand = "0.8.4"